# --- !Ups
create table "films" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "title" varchar not null,
    "length" int not null
);

create table "rooms" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "numberOfRows" int not null,
    "numberOfSeatsInRow" int not null
);

create table "screenings" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "roomId" bigint not null,
    "filmId" bigint not null,
    "dateAndTime" varchar not null
);

create table "seats" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "screeningId" bigint not null,
    "row" int not null,
    "numberSeat" int not null,
    "available" boolean not null
)



# --- !Downs
drop table "seats" if exists;
drop table "screenings" if exists;
drop table "rooms" if exists;
drop table "films" if exists;
