# --- !Ups
create table "films" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "title" varchar not null,
    "length" int not null
);

create table "rooms" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "numberOfRows" int not null,
    "numberOfSeatsInRow" int not null
);

# --- !Downs
drop table "rooms" if exists;
drop table "films" if exists;
